config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'
  get 'new/create'
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'artists#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :artists, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :search, to: 'artists#search'
    end

    resources :favorites, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :create, :destroy]
    
  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      get :pass, to: 'users#pass'
    end
  end

end

app/models/artist.rb
class Artist < ApplicationRecord

  mount_uploader :artist_image, ArtistImageUploader

  belongs_to :user
  
  has_many :artist_genres, dependent: :destroy
  has_many :get_genres, through: :artist_genres, source: :genre
  accepts_nested_attributes_for :artist_genres, allow_destroy: true

  has_many :artist_feelings, dependent: :destroy
  has_many :get_feelings, through: :artist_feelings, source: :feeling
  accepts_nested_attributes_for :artist_feelings, allow_destroy: true

  has_many :favorites, dependent: :destroy
  has_many :favoriters, through: :favorites, source: :user

  has_many :comments, dependent: :destroy
  has_many :commenters, through: :comments, source: :user

  # ヘッダーの検索ボタンを押した時に動作する
  def self.search(name, genre_ids, feeling_ids)
    ret = []
    ret2 = []
    ret3 = []
    
    if !name.empty?
      ret = Artist.where(['name LIKE ?', "%#{name}%"])
    end
  
    if genre_ids
      ret2 = Genre.genre_registers_search(genre_ids)
    end
  
    if feeling_ids
      ret3 = Feeling.feeling_registers_search(feeling_ids)
    end
    
    return self.ret_check(ret,ret2,ret3)
  end
  
  private
  
  def self.ret_check(ret,ret2,ret3)
    ret_str = []
    
    if !ret.empty?
      ret_str = ret
    end
    
    if !ret2.empty?
      if ret_str.empty?
        ret_str = ret_str | ret2
      else
        ret_str = ret_str & ret2
      end
    end
    
    if !ret3.empty?
      if ret_str.empty?
        ret_str = ret_str | ret3
      else
        ret_str = ret_str & ret3
      end
    end
    
    return ret_str
  end
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # ページネーションする表示コンテンツ閾値
  PAGE_CONTENT = 12
  
  before_action :genre_feeling_set, only: [:index, :show, :new, :search]
  
  def index
    @artists = Artist.all.order(id: :desc).page(params[:page]).per(PAGE_CONTENT)
  end
  
  def search
    # 検索機能 
    artist_name = params[:name]
    genre_ids = params[:genres]      
    feeling_ids = params[:feelings]  
    
    if artist_name.empty? && genre_ids.nil? && feeling_ids.nil?
      flash[:danger] = '検索条件を指定してください。'
      redirect_to root_path
    end
    
    @search_results = Artist.search(artist_name, genre_ids, feeling_ids)
  end

  def show
    @show_artist = Artist.find(params[:id])
    @up_user = User.find(@show_artist.user_id) 
    # コメント投稿用
    @comment = Comment.new
  end

  def new
    @artist = Artist.new
    @artist.artist_genres.build
    @artist.artist_feelings.build
  end
  
  def create
    
    @artist = Artist.new(artist_params)

    if @artist.save
      # 選択されたgenreを処理する
      if params[:artist][:artist_genres_attributes]
        params[:artist][:artist_genres_attributes]["0"][:genre_id].each do |e|
          @artist.artist_genres.create!(artist_id: :id, genre_id: e)
        end 
      end

      # 選択されたfeelingを処理する
      if params[:artist][:artist_feelings_attributes]
        params[:artist][:artist_feelings_attributes]["0"][:feeling_id].each do |e|
          @artist.artist_feelings.create!(artist_id: :id, feeling_id: e)
        end
      end

      flash[:success] = 'アーティストを登録しました。'
      redirect_to @artist
    else
      flash.now[:danger] = 'アーティストの登録に失敗しました。'
      genre_feeling_set
      render action: :new
    end

  end

  def edit
  end
  
  def update
  end
  
  private
  
  def genre_feeling_set 
    @disp_genres = Genre.all
    @disp_feelings = Feeling.all
  end
  
  def artist_params
    params.require(:artist).permit(:name, :description, :artist_image).merge(user_id: current_user.id)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist_card.html.erb
<div class="card-wrapper_ text-center container">
  <div class="row">
    <% artists.each do |artist| %>
    <div class="col-12 col-sm-6 col-lg-4">
      <div class="card-content_ card m-3 shadow-sm d-inline-block">
        <a href="<%= artist_path(artist) %>" width="100%">
          <%# imageカラムにサムネイルが設定されているか %>
          <% if artist.artist_image.url %>
            <%# TODO:DBに登録されている画像 %>
            <%= image_tag artist.artist_image.url, class: "card-img-top"%>
          <% elsif %>
            <%# デフォルト画像を使用 %>
            <img src="/assets/default-artist-header.png" class="card-img-top">
          <% end %>
          <div class="card-body border-top">
            <p><i class="fas fa-heart text-danger"></i><span class="ml-2"><%= artist.favorites.count %></span></p>
            <h5 class="card-title"><%= artist.name %></h5>
            <p class="card-text"><%= artist.description %></p>
          </div>
        </a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/artists/_artist_header.html.erb
<!--header jumbotron-->
<div class="jumbotron my-2 mx-5 h-100　container">
  <p class="lead">音楽との出会いを豊かに。</p>
  <%= form_with(url: search_artists_path, method: 'get', local: true) do |f| %>
    <div class="form-group">
      <div class="row">
        <div class="offset-2 col-8 offset-md-6 col-md-4">
          <%= f.text_field :name, class: 'form-control form-control-sm', placeholder: 'アーティスト名を検索' %>
          <a class="btn btn-info btn-sm text-light"
            data-toggle="collapse"
            href="#condition"
            role="button"
            aria-expand="false"
            aria-controls="#condition">条件付き検索</a>
            
          <div class="collapse" id="condition">
            <div class="card card-body bg-light">
              <h5>ジャンル</h5>
              <% @disp_genres.each do |genre|%>
                <span><%= f.check_box :genres, {multiple: true}, genre.id, nil %>
                <%= genre.genre %></span>
              <% end %>
              <h5>気分</h5>
              <% @disp_feelings.each do |feeling| %>
                <span><%= f.check_box :feelings, {multiple: true}, feeling.id, nil %>
                <%= feeling.feeling %></span>
              <% end %>
            </div>
          </div>
          
          <%= f.submit '検索', class: 'btn btn-light d-block ml-auto mt-1' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<%= render 'artists/artist_header'%>
<div class="mx-auto border-top">
  <!--navigation-->
  <ul class="nav nav-tabs justify-content-center bg-light artist-tab mb-5">
    <li class="nav-item"><%= link_to 'さがす', root_path, class: 'nav-link active'%></li>
    <li class="nav-item"><%= link_to 'ひろめる', new_artist_path, class: 'nav-link'%></li>
  </ul>
  <!--artist view(card content)-->
  <%= render 'artist_card', artists: @artists %>
  <%= paginate @artists %>
</div>

app/views/artists/new.html.erb
<%= render 'artists/artist_header' %>
<div class="mx-auto border-top">
  <ul class="nav nav-tabs justify-content-center bg-light artist-tab">
    <li class="nav-item"><%= link_to 'さがす', root_path, class: 'nav-link'%></li>
    <li class="nav-item"><%= link_to 'ひろめる', new_artist_path, class: 'nav-link active'%></li>
  </ul>
  <div class="row">
    <div class="col-sm-6 offset-sm-3 mb-5">
      <!--ログイン中であれば登録画面を出す-->
      <% if logged_in? %>
        <div class="alert alert-primary text-center mt-4" role="alert">新規アーティスト登録</div>
        <%= form_with(model: @artist, local:true ) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'アーティスト名', class: "font-weight-bold"%>
            <span class="badge badge-danger">必須</span>
            <%= f.text_field :name, class: "form-control", placeholder: "アーティスト名を入力してください", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :description, '説明', class: "font-weight-bold" %>
            <span class="badge badge-danger">必須</span>
            <%= f.text_area :description, class: "form-control", size: "20x10", placeholder: "説明文を入力してください", required: true %>
          </div>
            
          <div class="form-group">
            <%= f.label :artist_image, 'アーティスト画像', class: "font-weight-bold"%><br>
            <%= f.file_field :artist_image %>
          </div>
  
          <div class="row">
            <div class="form-group col-md-4">
              <%= f.fields_for :artist_genres do |i|%>
                <%= i.label :genre_id, 'ジャンル', class: "font-weight-bold" %>
                <% @disp_genres.each do |genre| %>
                  <div>
                    <%= i.check_box :genre_id, {multiple: true}, genre.id, false %>
                    <%= genre.genre %>
                  </div>
                <% end %>
              <% end %>  
            </div>
            <div class="form-group offset-md-1 col-md-4">
                <%= f.fields_for :artist_feelings do |i|%>
                  <%= i.label :feeling_id, '気分', class: "font-weight-bold"%>
                  <% @disp_feelings.each do |feeling| %>
                    <div>
                      <%= i.check_box :feeling_id, {multiple: true}, feeling.id, false %>
                      <%= feeling.feeling %>
                    </div>
                  <% end %>
                <% end %>
            </div>
          </div>
          
          <%= f.submit 'アーティストを登録', class: 'btn btn-primary' %>
        <% end %>
      <!--ログイン中でなければアラート-->
      <% else %>
        <%= render 'layouts/need_login' %>
      <% end %>
    </div>
  </div>
</div>

app/views/artists/search.html.erb
<%= render 'artists/artist_header'%>

<!--artist view(card content)-->
<!--検索結果が１件以上-->
<% if @search_results %>
  <%= render 'artist_card', artists: @search_results %>
<!--検索結果なし-->
<% else %>
  <h1>ないよーん</h1>
<% end %>

app/views/artists/show.html.erb
<%= render 'artists/artist_header'%>
<div class="show-wrapper_ border-top">
  <div class="show-content_ mx-auto my-5">
    <!--artist name-->
    <div class="alert alert-info my-2 h2 text-center"><%= @show_artist.name %></div>
    <!--artist image-->
    <div class="card shadow d-inline-block w-100">
      <div class="adjust-box_ box_">
        <div class="artist-img_">
          <!-- アーティスト画像が見つかればその画像を表示 -->
          <!-- アーティスト画像が登録されていなければデフォルト画像 -->
          <% if @show_artist.artist_image.url %>
            <%= image_tag @show_artist.artist_image.url, class: "artist-img_"%>
          <% else %>
            <img src="/assets/default-artist-header.png" alt="アーティストデフォルト画像" class="artist-img_">
          <% end %>
          <div class="artist-tag_ ml-2">
            <!-- ジャンルが登録されていれば表示 -->
            <p class="genre_">
              <% if @show_artist.get_genres %>
                <% @show_artist.get_genres.each do |genre| %>
                  <span class="badge badge-primary p-2 mr-2"><%= genre.genre %></span>
                <% end %>
              <% end %>
            </p>
            <!-- 気分が登録されていれば表示 -->
            <p class="feeling_">
            　<% if @show_artist.get_feelings %>
                <% @show_artist.get_feelings.each do |feeling| %>
                  <span class="badge badge-success p-2 mr-2"><%= feeling.feeling %></span>
                  <% end %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex flex-row justify-content-between align-items-center my-1 mx-2 pt-3 border-top">
          <!--like button-->
          <div id="favorite">
            <%= render 'favorites/favorite_button', artist: @show_artist %>
          </div>
          <!--upload user-->
          <div class="up-user_">
            <span class="h5 d-inline-block"><strong>投稿者</strong>
            <%# <img src="/assets/default-user-icon.png" class="rounded-circle border border-dark" width="50px" height="50px"> %>
            <%= render 'users/user_icon', { user: @up_user, w: 50, h: 50 } %>
            <%= link_to "#{@up_user.name}", user_path(@up_user) %>さん
            </span>
          </div>
        </div>
        <div class="artist_description_ h6 mx-2 mt-5">
          <span class="badge badge-dark">説明</span>
          <div class="border border-dark rounded p-3 shadow-sm">
            <%= @show_artist.description %>
          </div>
        </div>
      </div>
    </div>
    <div class="card shadow d-inline-block w-100 mt-4">
      <!-- comments new -->
      <%= render 'comments/new', artist: @show_artist%>
      <!-- comments index -->
      <!-- new comment is display top -->
      <%= render 'comments/index', { comments: @show_artist.comments.reverse, from_user: @show_artist.commenters.reverse } %>
    </div>
  </div>
</div>