config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'
  get 'new/create'
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'artists#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :artists, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :search, to: 'artists#search'
    end

    resources :favorites, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :create, :destroy]
    
  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      get :pass, to: 'users#pass'
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :artist
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :set_artist, only: [:create, :destroy]

  def create
    current_user.favorite(@artist)
    flash[:success] = 'お気に入りに登録しました'
  end

  def destroy
    current_user.unfavorite(@artist)
    flash[:success] = 'お気に入りを解除しました'
  end

  private
  
  def set_artist 
    @artist = Artist.find(params[:artist_id])
    @show_artist = Artist.find(params[:artist_id]) 
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_button.html.erb
<div class="like-button_ ml-3 text-center">
  <%# ログイン中 %>
  <% if current_user %>
    <strong>いいね！</strong>- Tap here!<br>
    <%# いいね済 %> 
    <% if current_user.favoriting?(artist) %>
      <div class="LikesIcon d-inline-block rounded-circle p-3 mt-2 on">
        <%= link_to(artist_favorite_path(@show_artist, artist.id), method: :delete, remote: true) do %>
          <i class="fas fa-heart LikesIcon-fa-heart heart"></i>
        <% end %>
      </div>
    <%# 未いいね %>
    <% else %>
      <div class="LikesIcon d-inline-block rounded-circle p-3 mt-2">
        <%= link_to(artist_favorites_path(@show_artist), method: :post, remote: true) do %>
          <i class="far fa-heart LikesIcon-fa-heart"></i>
        <% end %>
      </div>
    <% end %>
    <span class="font-weight-bold m-2 h4"><%= artist.favorites.count %></span>

  <%# 未ログイン %>
  <% else %>
    <div class="alert alert-light">
      <strong class="d-block">ログインしてお気に入り登録</strong>
        <%= link_to 'ログイン', login_path, class: 'nav-item btn btn-outline-primary m-1 mt-3' %>
    </div>
  <% end %>

  <%# TODO: いいねの数表示 %>
</div>

app/views/favorites/create.js.erb
$('#favorite').html("<%= j(render 'favorites/favorite_button', artist: @show_artist) %>");

app/views/favorites/destroy.js.erb
$('#favorite').html("<%= j(render 'favorites/favorite_button', artist: @show_artist) %>");