config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'
  get 'new/create'
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'artists#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :artists, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :search, to: 'artists#search'
    end

    resources :favorites, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :create, :destroy]
    
  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      get :pass, to: 'users#pass'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :user_image, UserImageUploader

  before_save { self.email.downcase! }
  validates :name, presence: true
  validates :name, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
    
  has_many :artists

  has_many :favorites
  has_many :favoritings, through: :favorites, source: :artist

  has_many :comments
  has_many :commentings, through: :comments, source: :artist

  def favorite(artist)
    self.favorites.find_or_create_by(artist_id: artist.id)
  end

  def unfavorite(artist)
    favorite = self.favorites.find_by(artist_id: artist.id)
    favorite.destroy if favorite
  end

  def favoriting?(artist)
    self.favoritings.include?(artist)
  end

  def comment(artist_id,content)
    self.comments.find_or_create_by(artist_id: artist_id, content: content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :pass, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def show
  end

  def edit 
  end

  def pass
  end

  def update

    # パスワード変更時の現在パスワード一致チェック
    if params[:user][:password_before]
      unless @user.authenticate(params[:user][:password_before])
        
        flash.now[:danger] = '現在のパスワードが誤っています'
        render :pass
        return
      end
    end

    if @user.update(user_params)
      flash[:success] = 'ユーザ情報を変更しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ情報の変更に失敗しました'
      render :edit
    end

  end

 private

  def user_params
    params.require(:user).permit(:name, :email, :user_image, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_user_icon.html.erb
<%# 画像が登録されている→登録されている画像　されていない→デフォルト画像 %>
<%if user.user_image.url %>
  <%= image_tag user.user_image.url, class: 'rounded-circle border border-secondary shadow mx-1', width: "#{w}px", height: "#{h}px" %>
<% else %>  
  <%= image_tag '/assets/default-user-icon.png', class: 'rounded-circle border border-secondary shadow mx-1', width: "#{w}px", height: "#{h}px" %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1 class="mt-5 mb-3">ユーザ情報編集</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :user_image, 'プロフィール写真'%>
        <%= f.file_field :user_image, class: 'd-block' %>
      </div>
    
      <div class="form-group">
        <%= f.label :name, 'ユーザ名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
  
      <%= f.submit '上記の内容で編集', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1 class="mt-5 mb-3">アカウント登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, 'ユーザ名' %>
        <span class="badge badge-danger">必須</span>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <span class="badge badge-danger">必須</span>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <span class="badge badge-danger">必須</span>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認用)' %>
        <span class="badge badge-danger">必須</span>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "確認のため同じパスワードを入力してください" %>
      </div>
  
      <%= f.submit 'アカウント登録', class: 'btn btn-primary btn-block' %>
    <% end %>
    
    <p class="mt-2">アカウントをお持ちの方は <%= link_to 'ログイン', login_path %></p>
  </div>
</div>

app/views/users/pass.html.erb
<div class="text-center">
  <h1 class="mt-5 mb-3">パスワード変更</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :password_before, '現在のパスワード'%>
        <span class="badge badge-danger">必須</span>
        <%= f.password_field :password_before, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :name, '新しいパスワード' %>
        <span class="badge badge-danger">必須</span>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, '新しいパスワード(確認用)' %>
        <span class="badge badge-danger">必須</span>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "確認のため同じパスワードを入力してください" %>
      </div>
  
      <%= f.submit 'パスワードを変更', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1 class="mt-5 mb-3">ユーザプロフィール</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3 text-center">

    <div class="mb-4">
      <%# <img src="/assets/default-user-icon.png" class="rounded-circle border border-dark" width="100px" height="100px"> %>
      <%= render 'users/user_icon', { user: @user, w: 130, h: 130 } %>
    </div>
    <div class="mb-4">name : <%= @user.name %></div>
    <div class="mb-4">email : <%= @user.email %></div>

    <%# 表示中のユーザとcurrent_userが一致してたら編集ボタン表示 %>
    <% if current_user == @user %>
      <%= link_to 'ユーザ情報編集', edit_user_path, class: 'btn btn-primary' %>
      <%# under construction %>
      <%= link_to 'パスワード変更', pass_user_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>