config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'
  get 'new/create'
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'artists#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :artists, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :search, to: 'artists#search'
    end

    resources :favorites, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :create, :destroy]
    
  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      get :pass, to: 'users#pass'
    end
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<!--ロゴ、ログイン関連UIを表示するヘッダー（全画面にて表示）-->
<header class="border-bottom">
  <div class="container">
    <nav class="navbar navbar-expand-sm navbar-light row">
      <a href="/" class="navbar-brand col-6 col-md-4 logo_">
        <img src="/assets/logo.svg" width="60" height="60" class="d-inline-block align-middle" alt="サイトロゴ">
        ArtistMining
      </a>
      <div class="navbar-nav offset-md-2 col-md-6 col-sm-8">
        <% if logged_in? %>
          　<span class="mr-2">
              <strong>ログイン中</strong>
              <%# 画像が登録されている→登録されている画像　されていない→デフォルト画像 ★ここテンプレート可したい%>
              <%# <img src="/assets/default-user-icon.png" class="rounded-circle border border-dark mx-1" width="50px" height="50px"> %>
              <%= render 'users/user_icon', { user: current_user, w: 50, h: 50 } %>
              <%= link_to "#{current_user.name}", user_path(current_user) %>さん 
              <%# ここまで。テンプレートに表示すべきユーザのインスタンスを渡す　ヘッダー→currentuser, artist/show→@up_user %>
            </span>
            <div class="btn-group">
              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</button>
              <div class="dropdown-menu">
                <%= link_to 'マイページ', user_path(current_user), class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %>
              </div>
            </div>
        <% else %>
          <%= link_to 'ログイン', login_path, class: 'nav-item btn btn-outline-primary m-1' %>
          <%= link_to 'アカウント登録', new_user_path, class: 'nav-item btn btn-outline-secondary m-1' %>
        <% end %>
      <div>  
    </nav>
  </div>
</header>

app/views/layouts/_need_login.html.erb
<div class="card mt-3">
  <div class="card-body">
    <h5 class="card-title"><i class="fas fa-exclamation-triangle mr-1"></i>こちらをご利用いただくにはログインしてください</h5>
    <p class="card-text">アーティスト投稿機能をご利用いただくには、ログインが必要です。</p>
    <%= link_to 'ログイン', login_path, class: 'btn btn-outline-primary m-1' %>
    <%= link_to 'アカウント登録', new_user_path, class: 'btn btn-outline-secondary m-1' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ArtistMining</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="icon" href="assets/headphone.svg" type="image/svg+xml">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@600&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>